### ISSUE TITLE
Fail to run BLIP2 evaluation script on coco caption

### ISSUE THREAD

**Issue by kebijuelun** [salesforce/LAVIS#116]
Thanks for the great work.
I install the LAVIS from source (commit 2b6c6caf223e1a9a5139842d3191cad4166466b8) 
 followed the step in  readme, and fail to run BLIP2 evaluation script on v100 machine when running `sh run_scripts/blip2/eval/eval_cap_coco_flant5xl.sh`:

```bash
Traceback (most recent call last):                                                                                                                                                    
  File "evaluate.py", line 92, in <module>                                                                                                                                            
    main()                                                                                                                                                                            
  File "evaluate.py", line 88, in main                                                                                                                                                
    runner.evaluate(skip_reload=True)                                                                                                                                                 
  File "/data/github_code/LAVIS/lavis/runners/runner_base.py", line 401, in evaluate                                                                                                  
    test_logs[split_name] = self.eval_epoch(                                                                                                                                          
  File "/home/liuweizhou/miniconda3/envs/lavis/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context                                                 
    return func(*args, **kwargs)                                                                                                                                                      
  File "/data/github_code/LAVIS/lavis/runners/runner_base.py", line 449, in eval_epoch                                                                                                
    results = self.task.evaluation(model, data_loader)                                                                                                                                
  File "/data/github_code/LAVIS/lavis/tasks/base_task.py", line 90, in evaluation                                                                                                     
    eval_output = self.valid_step(model=model, samples=samples)                                                                                                                       
  File "/data/github_code/LAVIS/lavis/tasks/captioning.py", line 51, in valid_step                                                                                                    
    captions = model.generate(                                                                                                                                                        
  File "/home/liuweizhou/miniconda3/envs/lavis/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context                                                 
    return func(*args, **kwargs)                                                                                                                                                      
  File "/data/github_code/LAVIS/lavis/models/blip2_models/blip2_t5.py", line 174, in generate                                                                                         
    image_embeds = self.ln_vision(self.visual_encoder(image))                                                                                                                         
  File "/home/liuweizhou/miniconda3/envs/lavis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                                      
    return forward_call(*input, **kwargs)                                                                                                                                             
  File "/data/github_code/LAVIS/lavis/models/eva_vit.py", line 352, in forward                                                                                                        
    x = self.forward_features(x)                                                                                                                                                      
  File "/data/github_code/LAVIS/lavis/models/eva_vit.py", line 341, in forward_features                                                                                               
    x = blk(x, rel_pos_bias)                                                                                                                                                          
  File "/home/liuweizhou/miniconda3/envs/lavis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                                      
    return forward_call(*input, **kwargs)                                                                                                                                             
  File "/data/github_code/LAVIS/lavis/models/eva_vit.py", line 177, in forward                                                                                                        
    x = x + self.drop_path(self.attn(self.norm1(x), rel_pos_bias=rel_pos_bias))                                                                                                       
  File "/home/liuweizhou/miniconda3/envs/lavis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                                      
    return forward_call(*input, **kwargs)                                                                                                                                             
  File "/data/github_code/LAVIS/lavis/models/eva_vit.py", line 130, in forward
    attn = (q @ k.transpose(-2, -1))
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
```

The only change is to change `--nproc_per_node=8` to `--nproc_per_node=1`, so I can evaluate with a single V100 card.

- I have check the shape of the tensor:
```
In [1]: k.shape
Out[1]: torch.Size([1, 16, 677, 88])
In [2]: q.shape
Out[2]: torch.Size([1, 16, 677, 88])
In [3]: attn = (q @ k.transpose(-2, -1))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 1
----> 1 attn = (q @ k.transpose(-2, -1))
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
```

- some related package version:
```
cuda 11.4 
cudnn v8.2.1
torch                    1.13.1
torchvision              0.14.1
```

How can I reproduce the evaluation of BLIP2, Could you please give some information about the environmental requirements?

**Comment by dxli94** [comment]
@kebijuelun, thanks for the issue.

Can you share how the issue was resolved? Thanks.

**Comment by kebijuelun** [comment]
> Can you share is the issue resolved? If so, how did you resolve it? The large audience may be interested.

I don't know the specific reason for this problem. 
My current solution is to change a machine and change the cuda version （cuda 10.2, cudnn 8.0.4）, and not to  use the conda installation environment (with /usr/local/bin/pip install).

I would appreciate it if someone could tell me the essence of the above problems.

**Comment by yiren-jian** [comment]
Had the same issue. Solved by google searching ending up [here](https://github.com/coqui-ai/TTS/issues/1517)

`unset LD_LIBRARY_PATH`
