### ISSUE TITLE
How to fix this errors ?  sd-webui-blip2

### ISSUE THREAD

**Issue by oaefou** [salesforce/LAVIS#171]
Traceback (most recent call last):
  File "C:\SD\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\SD\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\SD\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\SD\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\SD\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\SD\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\SD\extensions\sd-webui-blip2\scripts\main.py", line 71, in gen_caption
    image = vis_processors["eval"](image).unsqueeze(0).to(device)
KeyError: 'eval'

**Comment by Fym68** [comment]
Have you solved this problem? How did you solve it?
