### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

### ISSUE THREAD

**Issue by waterpeople** [salesforce/LAVIS#386]
when I use download_sbu.py
i have encounter this error
Traceback (most recent call last):
  File "/root/lavis/lavis/datasets/download_scripts/download_sbu.py", line 37, in fetch_single_image
    with urllib.request.urlopen(request, timeout=timeout) as req:
  File "/root/anaconda3/envs/lavis/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/root/anaconda3/envs/lavis/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/root/anaconda3/envs/lavis/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/root/anaconda3/envs/lavis/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/root/anaconda3/envs/lavis/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/root/anaconda3/envs/lavis/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

how can i solve it

**Comment by macqueen09** [comment]
if internet couldn't hit huggingface, I will use https://hf-mirror.com  , but I don't know how to change url https://hf-mirror.com and how to use offline file dir  that i has download model file in huggingface before.
