### ISSUE TITLE
Error about Qformer or instructBlip & vicuna v1.1 version

### ISSUE THREAD

**Issue by CCYChongyanChen** [salesforce/LAVIS#399]
Thank you for the great work. 
On the fastchat page it only lists v1.3 now. https://github.com/lm-sys/FastChat#model-weights
How could we get the vicuna v1.1 version?
Also, is this delta-v1.1? or not delta?
Thanks!

**Comment by vishaal27** [comment]
I was able to get InstructBLIP-Vicuna versions running with these weights: 
- https://huggingface.co/TheBloke/vicuna-13B-1.1-HF
- https://huggingface.co/TheBloke/vicuna-7B-1.1-HF

The original weights can still be found here: https://github.com/lm-sys/FastChat/blob/main/docs/vicuna_weights_version.md
But the original weights are delta weights which have to be merged whereas the weights I provided above are the merged weights so it is less of a hassle to use those. I would recommend using them.

**Comment by CCYChongyanChen** [comment]
Thank you so much @vishaal27 

I am trying https://huggingface.co/TheBloke/vicuna-13B-1.1-HF
However, I met this error message: 


Traceback (most recent call last):
  File "instructBlip.py", line 23, in <module>
    model, vis_processors, _ = load_model_and_preprocess(
  File "/mnt/cache/LAVIS_NEW/LAVIS/lavis/models/__init__.py", line 200, in load_model_and_preprocess
    model = model_cls.from_pretrained(model_type=model_type)
  File "/mnt/cache/LAVIS_NEW/LAVIS/lavis/models/base_model.py", line 70, in from_pretrained
    model = cls.from_config(model_cfg)
  File "/mnt/cache/LAVIS_NEW/LAVIS/lavis/models/blip2_models/blip2_vicuna_instruct.py", line 707, in from_config
    model = cls(
  File "/mnt/cache/LAVIS_NEW/LAVIS/lavis/models/blip2_models/blip2_vicuna_instruct.py", line 68, in __init__
    self.Qformer, self.query_tokens = self.init_Qformer(
  File "/mnt/cache/LAVIS_NEW/LAVIS/lavis/models/blip2_models/blip2.py", line 54, in init_Qformer
    Qformer = BertLMHeadModel.from_pretrained(
  File "/home/aiscuser/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2604, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/aiscuser/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 461, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "/home/aiscuser/.local/lib/python3.8/site-packages/safetensors/torch.py", line 261, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[768]' is invalid for input of size 96


I have downloaded the vicuna-13B-1.1-HF weights and stored it here: 

<img width="498" alt="image" src="https://github.com/salesforce/LAVIS/assets/21120604/d1b38051-403d-457e-b28e-fb813caf583a">

I have changed the yaml file accordingly: 
<img width="323" alt="image" src="https://github.com/salesforce/LAVIS/assets/21120604/945c2e96-914d-4d4a-a226-1e01ee76310d">

Any idea of what is going on is appreciated. Thanks!

**Comment by CCYChongyanChen** [comment]
upgrading torch to 2.0 as well as transformers solves the issue

**Comment by ldfandian** [comment]
> * https://huggingface.co/TheBloke/vicuna-13B-1.1-HF

does it improve performance for your upgrading weight to vicuna-v1.3 ?
