### ISSUE TITLE
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 

### ISSUE THREAD

**Issue by Ryosuke0104** [salesforce/LAVIS#413]
I run this code:
`import torch
from PIL import Image
# setup device to use
device = torch.device("cuda") if torch.cuda.is_available() else "cpu"
# load sample image
raw_image = Image.open("./docs/_static/Confusing-Pictures.jpg").convert("RGB")
# display(raw_image.resize((596, 437)))

from lavis.models import load_model_and_preprocess
# loads InstructBLIP model
model, vis_processors, _ = load_model_and_preprocess(name="blip2_vicuna_instruct", model_type="vicuna13b", is_eval=True, device=device)
# prepare the image
image = vis_processors["eval"](raw_image).unsqueeze(0).to(device)`

and I got this error.

`/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1727: FutureWarning: Calling LlamaTokenizer.from_pretrained() with the path to a single file or url is deprecated and won't be possible anymore in v5. Use a model identifier or the path to a directory instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/projects/LAVIS/test.py", line 11, in <module>
    model, vis_processors, _ = load_model_and_preprocess(name="blip2_vicuna_instruct", model_type="vicuna13b", is_eval=True, device=device)
  File "/home/projects/LAVIS/lavis/models/__init__.py", line 200, in load_model_and_preprocess
    model = model_cls.from_pretrained(model_type=model_type)
  File "/home/projects/LAVIS/lavis/models/base_model.py", line 70, in from_pretrained
    model = cls.from_config(model_cfg)
  File "/home/projects/LAVIS/lavis/models/blip2_models/blip2_vicuna_instruct.py", line 707, in from_config
    model = cls(
  File "/home/projects/LAVIS/lavis/models/blip2_models/blip2_vicuna_instruct.py", line 82, in __init__
    self.llm_tokenizer = LlamaTokenizer.from_pretrained(llm_model, use_fast=False, truncation_side="left")
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 96, in __init__
    self.sp_model.Load(vocab_file)
  File "/opt/conda/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/opt/conda/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] `

I'm beginner of LLMs, so I can't fix it.
Please tell me how I can fix.

**Comment by TaoshuaiZ** [comment]
I had the same problem, did you solve it.
