### ISSUE TITLE
`IndexError: piece id is out of range` occur in training instructBLIP

### ISSUE THREAD

**Issue by greeksharifa** [salesforce/LAVIS#457]
Hi,
I'm training(Fine-tuning) instructBLIP, which of pretrained model is `instruct_blip_vicuna7b_trimmed.pth`, but I got `IndexError: piece id is out of range`.

This error maybe occur, token_id exceeds some max_token_id, when decoding texts, literally. 
Why this error occur, and how can I fix it?

```
python train.py --cfg-path FT.yaml
...(omitted)...
Train: data epoch: [0]  [5215/5216]  eta: 0:00:00  lr: 0.000003  loss: 0.0996  time: 0.6706  data: 0.0000  max mem: 31461
Train: data epoch: [0] Total time: 0:57:16 (0.6588 s / it)Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 0,
  "eos_token_id": 1,
  "pad_token_id": -1,
  "transformers_version": "4.28.0"
}

/home/work/.local/lib/python3.8/site-packages/transformers/generation/utils.py:1219: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 129, in main
    runner.train()
  File "LAVIS/lavis/runners/runner_base.py", line 371, in train
    val_log = self.eval_epoch(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "LAVIS/lavis/runners/runner_base.py", line 460, in eval_epoch
    results = self.task.evaluation(model, data_loader)
  File "LAVIS/lavis/tasks/base_task.py", line 99, in evaluation
    eval_output = self.valid_step(model=model, samples=samples)
  File "LAVIS/lavis/tasks/vqa.py", line 321, in valid_step
    answers = model.predict_answers(
  File "LAVIS/lavis/models/blip2_models/blip2_vicuna_instruct.py", line 417, in predict_answers
    output_text = self.generate(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "LAVIS/lavis/models/blip2_models/blip2_vicuna_instruct.py", line 377, in generate
    output_text = self.llm_tokenizer.batch_decode(outputs, skip_special_tokens=True)
  File "/home/work/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3446, in batch_decode
    return [
  File "/home/work/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3447, in <listcomp>
    self.decode(
  File "/home/work/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3486, in decode
    return self._decode(
  File "/home/work/.local/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 931, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/home/work/.local/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 912, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/home/work/.local/lib/python3.8/site-packages/transformers/models/llama/tokenization_llama.py", line 129, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)
  File "/opt/conda/lib/python3.8/site-packages/sentencepiece/__init__.py", line 501, in _batched_func
    return _func(self, arg)
  File "/opt/conda/lib/python3.8/site-packages/sentencepiece/__init__.py", line 494, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.
[main1:90991:0:91018] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x7f37bd40eb11)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 90991) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
train.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-27_09:43:50
  host      : main1
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 90991)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 90991
=======================================================
```

Thanks!

**Comment by Richar-Du** [comment]
Please refer to #483

**Comment by freckletonj** [comment]
In my use case, this only occurs when doing batches. This was an issue where the model was padding with `-1`. The token `1 == ''`, so you can replace those with that.

Here's the line number for me:
https://github.com/salesforce/LAVIS/blob/main/lavis/models/blip2_models/blip2_vicuna_instruct.py#L372

And the code:

```python
        outputs[outputs == 0] = 2 # convert output id 0 to 2 (eos_token_id)
        outputs[outputs == -1] = 1 # convert improper tokens to ''
```
