### ISSUE TITLE
AttributeError: 'BlipDiffusion' object has no attribute 'edit'

### ISSUE THREAD

**Issue by wuliebucha** [salesforce/LAVIS#481]
there is no real image editing code ?

Traceback (most recent call last):
  File "zero_shot_editing.py", line 38, in <module>
    output = model.edit(
  File "/home/jovyan/wuliebucha-bucha-home1/miniconda3/envs/lavis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BlipDiffusion' object has no attribute 'edit'

**Comment by wuliebucha** [comment]
my code is old one, i have seen the update.
