### ISSUE TITLE
LAION dataset pretrained error

### ISSUE THREAD

**Issue by XipengY** [salesforce/LAVIS#521]
We modifed the config for pretrain on LAION dataset, we found that the dataset is "WebDataset", but we meet some errors when load dataset.
The config of datasets is:
******
datasets:
  laion2B_multi:
     build_info:
       storage: '**/laion115m/0000/{00000..00170}.tar'
******
And  the code runs into the function "self.task.train_epoch()" of "lavis/runners/runner_base.py"  meet some errors as below:
******
*** AttributeError: 'ChainDataset' object has no attribute 'items'
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    main()
  File "train.py", line 101, in main
    runner.train()
  File "LAVIS/lavis/runners/runner_base.py", line 369, in train
    train_stats = self.train_epoch(cur_epoch)
  File "LAVIS/lavis/runners/runner_base.py", line 431, in train_epoch
    data_loader=self.train_loader,
  File "LAVIS/lavis/runners/runner_base.py", line 329, in train_loader
    train_dataloader = self.dataloaders["train"]
  File "LAVIS/lavis/runners/runner_base.py", line 215, in dataloaders
    num_records = len(self.datasets[split_name])
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 276, in __len__
    total += len(d)  # type: ignore[arg-type]
TypeError: object of type 'DataPipeline' has no len()
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 9702) of binary: /opt/conda/bin/python
******
Is the config  incorrect?

**Comment by XipengY** [comment]
![image](https://github.com/salesforce/LAVIS/assets/17317650/3cec81c0-8ce4-4fbf-b3ca-cb02f09c3113)
 We found the train need len(dataloader), but WebDataset have no len, this repo not support WebDatasets?
Look forward to your reply.

**Comment by XiaohuJoshua** [comment]
same question

**Comment by XiaohuJoshua** [comment]
> ![image](https://user-images.githubusercontent.com/17317650/267521417-3cec81c0-8ce4-4fbf-b3ca-cb02f09c3113.png) We found the train need len(dataloader), but WebDataset have no len, this repo not support WebDatasets? Look forward to your reply.

have you solved the problem

**Comment by liweiyangv** [comment]
same question, have you solved？

**Comment by liweiyangv** [comment]
> We modifed the config for pretrain on LAION dataset, we found that the dataset is "WebDataset", but we meet some errors when load dataset. The config of datasets is:
> 
> datasets: laion2B_multi: build_info: storage: '**/laion115m/0000/{00000..00170}.tar'
> 
> And the code runs into the function "self.task.train_epoch()" of "lavis/runners/runner_base.py" meet some errors as below:
> 
> *** AttributeError: 'ChainDataset' object has no attribute 'items' Traceback (most recent call last): File "train.py", line 105, in main() File "train.py", line 101, in main runner.train() File "LAVIS/lavis/runners/runner_base.py", line 369, in train train_stats = self.train_epoch(cur_epoch) File "LAVIS/lavis/runners/runner_base.py", line 431, in train_epoch data_loader=self.train_loader, File "LAVIS/lavis/runners/runner_base.py", line 329, in train_loader train_dataloader = self.dataloaders["train"] File "LAVIS/lavis/runners/runner_base.py", line 215, in dataloaders num_records = len(self.datasets[split_name]) File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 276, in **len** total += len(d) # type: ignore[arg-type] TypeError: object of type 'DataPipeline' has no len() ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 9702) of binary: /opt/conda/bin/python
> 
> Is the config incorrect?

hello, i met the same question, have you solved it?
