### ISSUE TITLE
Issues Encountered while Training Custom Dataset on Blip2

### ISSUE THREAD

**Issue by chunill** [salesforce/LAVIS#598]
Hi, 

I'm currently trying to create a new dataset, but I encounter some problems, I would appreciate it if you could take a moment to explain.  I referred to this following [document](https://opensource.salesforce.com/LAVIS//latest/tutorial.datasets.html), totally followed the provided instructions. However, the results are not as expected.

I customized the dataset according to the document and used the final command:

`python3 train.py --cfg-path /home/yces980096/NSTC/LAVIS/lavis/projects/blip2/train/taiwan_caption.yaml`

to load the configuration file. However, an error occurred:

```
/home/yces980096/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yces980096/.local/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda9SetDeviceEi'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yces980096/.local/lib/python3.8/site-packages/diffusers/models/cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
  deprecate(
Not using distributed mode
2023-11-29 16:01:14,573 [INFO]
=====  Running Parameters    =====
2023-11-29 16:01:14,573 [INFO] {
    "accum_grad_iters": 1,
    "amp": true,
    "batch_size_eval": 4,
    "batch_size_train": 12,
    "device": "cuda",
    "dist_url": "env://",
    "distributed": false,
    "evaluate": false,
    "init_lr": 1e-05,
    "lr_sched": "linear_warmup_cosine_lr",
    "max_epoch": 5,
    "max_len": 30,
    "min_len": 8,
    "min_lr": 0,
    "num_beams": 5,
    "num_workers": 4,
    "output_dir": "output/BLIP2/Caption_coco",
    "resume_ckpt_path": null,
    "seed": 42,
    "task": "captioning",
    "test_splits": [
        "test"
    ],
    "train_splits": [
        "train"
    ],
    "valid_splits": [
        "val"
    ],
    "warmup_lr": 1e-08,
    "warmup_steps": 1000,
    "weight_decay": 0.05,
    "world_size": 1
}
2023-11-29 16:01:14,573 [INFO]
======  Dataset Attributes  ======
2023-11-29 16:01:14,573 [INFO]
======== taiwan_captions =======
2023-11-29 16:01:14,574 [INFO] {
    "build_info": {
        "annotations": {
            "test": {
                "storage": "taiwan_caption_data/test.json",
                "url": "taiwan_caption_data/test.json"
            },
            "train": {
                "storage": "taiwan_caption_data/train.json",
                "url": "taiwan_caption_data/train.json"
            },
            "val": {
                "storage": "taiwan_caption_data/val.json",
                "url": "taiwan_caption_data/val.json"
            }
        },
        "images": {
            "storage": "taiwan_caption_data/image"
        }
    },
    "data_type": "images",
    "dataset_card": "dataset_card/taiwan_caption.md",
    "text_processor": {
        "eval": {
            "name": "blip_caption"
        },
        "train": {
            "name": "blip_caption",
            "prompt": "a photo of "
        }
    },
    "vis_processor": {
        "eval": {
            "image_size": 224,
            "name": "blip_image_eval"
        },
        "train": {
            "image_size": 224,
            "name": "blip2_image_train"
        }
    }
}
2023-11-29 16:01:14,574 [INFO]
======  Model Attributes  ======
2023-11-29 16:01:14,574 [INFO] {
    "arch": "blip2_opt",
    "drop_path_rate": 0,
    "finetuned": "",
    "freeze_vit": true,
    "image_size": 224,
    "load_finetuned": false,
    "model_type": "pretrain_opt2.7b",
    "num_query_token": 32,
    "opt_model": "facebook/opt-2.7b",
    "pretrained": "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_opt2.7b.pth",
    "prompt": "",
    "use_grad_checkpoint": true,
    "vit_precision": "fp16"
}
2023-11-29 16:01:14,574 [INFO] Using existing file /home/yces980096/NSTC/LAVIS/lavis/../taiwan_caption_data/train.json.
2023-11-29 16:01:14,574 [INFO] Using existing file /home/yces980096/NSTC/LAVIS/lavis/../taiwan_caption_data/val.json.
2023-11-29 16:01:14,574 [INFO] Using existing file /home/yces980096/NSTC/LAVIS/lavis/../taiwan_caption_data/test.json.
2023-11-29 16:01:14,574 [INFO] Building datasets...
2023-11-29 16:01:25,900 [INFO] freeze vision encoder
2023-11-29 16:02:15,641 [INFO] load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_opt2.7b.pth
2023-11-29 16:02:15,643 [INFO] Start training
2023-11-29 16:02:16,787 [INFO] dataset_ratios not specified, datasets will be concatenated (map-style datasets) or chained (webdataset.DataPipeline).
2023-11-29 16:02:16,787 [INFO] Loaded 1552 records for train split from the dataset.
2023-11-29 16:02:16,787 [INFO] Loaded 193 records for val split from the dataset.
2023-11-29 16:02:16,787 [INFO] Loaded 193 records for test split from the dataset.
2023-11-29 16:02:16,791 [INFO] number of trainable parameters: 107133696
2023-11-29 16:02:16,791 [INFO] Start training epoch 0, 129 iters per inner epoch.
/home/yces980096/.local/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Train: data epoch: [0]  [  0/129]  eta: 0:04:14  lr: 0.000000  loss: 3.5981  time: 1.9691  data: 0.0000  max mem: 10303
Train: data epoch: [0]  [ 50/129]  eta: 0:01:09  lr: 0.000001  loss: 3.3890  time: 0.8564  data: 0.0000  max mem: 11141
Train: data epoch: [0]  [100/129]  eta: 0:00:25  lr: 0.000001  loss: 3.2050  time: 0.8595  data: 0.0000  max mem: 11141
Train: data epoch: [0]  [128/129]  eta: 0:00:00  lr: 0.000001  loss: 3.2647  time: 0.8646  data: 0.0000  max mem: 11141
Train: data epoch: [0] Total time: 0:01:52 (0.8686 s / it)
2023-11-29 16:04:08,844 [INFO] Averaged stats: lr: 0.0000  loss: 3.4134
2023-11-29 16:04:08,846 [INFO] Evaluating on val.
Evaluation  [ 0/49]  eta: 0:01:02    time: 1.2844  data: 0.2437  max mem: 11141
Evaluation  [10/49]  eta: 0:00:40    time: 1.0288  data: 0.0226  max mem: 11141
Evaluation  [20/49]  eta: 0:00:31    time: 1.0699  data: 0.0005  max mem: 11141
Evaluation  [30/49]  eta: 0:00:20    time: 1.0830  data: 0.0005  max mem: 11141
Evaluation  [40/49]  eta: 0:00:09    time: 1.0756  data: 0.0005  max mem: 11141
Evaluation  [48/49]  eta: 0:00:01    time: 1.0815  data: 0.0044  max mem: 11141
Evaluation Total time: 0:00:52 (1.0656 s / it)
2023-11-29 16:05:01,072 [WARNING] rank 0 starts merging results.
result file saved to /home/yces980096/NSTC/LAVIS/lavis/output/BLIP2/Caption_coco/20231129160/result/val_epoch0.json
Using downloaded and verified file: /home/yces980096/NSTC/LAVIS/lavis/../coco_gt/coco_karpathy_val_gt.json
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!

Loading and preparing results...
Traceback (most recent call last):
  File "train.py", line 103, in <module>
    main()
  File "train.py", line 99, in main
    runner.train()
  File "/home/yces980096/NSTC/LAVIS/lavis/runners/runner_base.py", line 377, in train
    val_log = self.eval_epoch(
  File "/home/yces980096/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/yces980096/NSTC/LAVIS/lavis/runners/runner_base.py", line 469, in eval_epoch
    return self.task.after_evaluation(
  File "/home/yces980096/NSTC/LAVIS/lavis/tasks/captioning.py", line 74, in after_evaluation
    metrics = self._report_metrics(
  File "/home/yces980096/NSTC/LAVIS/lavis/common/dist_utils.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/home/yces980096/NSTC/LAVIS/lavis/tasks/captioning.py", line 87, in _report_metrics
    coco_val = coco_caption_eval(coco_gt_root, eval_result_file, split_name)
  File "/home/yces980096/NSTC/LAVIS/lavis/tasks/captioning.py", line 130, in coco_caption_eval
    coco_result = coco.loadRes(results_file)
  File "/home/yces980096/.local/lib/python3.8/site-packages/pycocotools/coco.py", line 327, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set
```

It appeared `AssertionError:Results do not correspond to the current coco set` . I searched it online, and I found that this error often occurs when the image IDs and file names are not purely numeric. Thus I modified both my file names and the JSON file, but the error persists.

To address this, I examined the original code and identified the problematic section in `/lavis/tasks/captioning.py`:

```
def coco_caption_eval(coco_gt_root, results_file, split):
    urls = {
        "val": "https://storage.googleapis.com/sfr-vision-language-research/datasets/coco_karpathy_val_gt.json",
        "test": "https://storage.googleapis.com/sfr-vision-language-research/datasets/coco_karpathy_test_gt.json",
    }
    filenames = {
        "val": "coco_karpathy_val_gt.json",
        "test": "coco_karpathy_test_gt.json",
    }

    download_url(urls[split], coco_gt_root)
    annotation_file = os.path.join(coco_gt_root, filenames[split])

    # create coco object and coco_result object
    coco = COCO(annotation_file)
```

I would like to inquire about what does file "coco_karpathy_val_gt.json"  do?  What is its funtion, and can it be freely modified? Additionally, why is this error occurring? Is there anything specific that I might have been done incorrectly?

Thank you.

**Comment by lingjiao10** [comment]
Hi, i have the same problem when finetuning on custom datasets. I found that the the reason is the mismatch  of current task's annotation_file and results_file, the former is annotation of validation ds while the latter is evaluated results of  test ds. I' am trying to fix it right now.
