### ISSUE TITLE
Error : indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by Kartik0611** [salesforce/LAVIS#68]
Hello, thank you for your amazing work. I'm trying to use the LAVIS repo to finetune BLIP retrieval on my own dataset. I am facing an issue while training. I am using a server with 2 GPUs for training [server has 4 RTX 3090 GPUs].  

1) I am not able to get what is causing the 'indices should be either on cpu or on the same device as the indexed tensor (cpu)' error

2) How can I set distributed to False? 
    I tried setting the parameter "distributed : False" in "/retrieval_coco_ft.yaml", but still when I run train.py, it will print "distributed : True".

3) Since I am using only 2 GPUs I have set "--nproc_per_node = 2" and ran the code. 
    Instead of torch.distributed.run can I use CUDA_VISIBLE_DEVICES and run the code?

Error message for the 1st point : 

File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/LAVIS/train.py", line 104, in <module>
    main()
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/LAVIS/train.py", line 100, in main
    runner.train()
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/LAVIS/lavis/runners/runner_base.py", line 360, in train
    val_log = self.eval_epoch(
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/BLIP/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/LAVIS/lavis/runners/runner_base.py", line 449, in eval_epoch
    results = self.task.evaluation(model, data_loader)
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/LAVIS/lavis/tasks/retrieval.py", line 34, in evaluation
    score_i2t, score_t2i = model.compute_sim_matrix(data_loader, task_cfg=self.cfg)
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/LAVIS/lavis/models/blip_models/blip_retrieval.py", line 396, in compute_sim_matrix
    return compute_sim_matrix(model=self, data_loader=data_loader, k_test=k_test)
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/LAVIS/lavis/models/albef_models/__init__.py", line 178, in compute_sim_matrix
    encoder_output = image_feats[topk_idx].to(model.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (CPU)

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1771487 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1771488 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1771490 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 2 (pid: 1771489) of binary: /mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/BLIP/bin/python
Traceback (most recent call last):
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/BLIP/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/BLIP/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/BLIP/lib/python3.10/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/BLIP/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/BLIP/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/BLIP/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/BLIP/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/44b643af-38ed-4d24-abcc-00e81b36025c/kartik/BLIP/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-12-10_17:44:58
  host      : ipcvserver4-Super-Server
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1771489)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by dxli94** [comment]
Hi @Kartik0611 , thanks for your interest.

Could you first help to confirm can you finetune BLIP model on datasets we support, such as COCO-retrieval and Flickr?

Thanks.

**Comment by dxli94** [comment]
Hi @Kartik0611 ,

Please find the fix in https://github.com/salesforce/LAVIS/commit/31944b1242b8669a3f5f9ec9adc523cbe75aeda9.

This issue occurred in higher torch versions.

Thanks for raising this.
