### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by slrhs** [salesforce/LAVIS#693]
Have you ever encountered this problem with friends? How can I solve it？Thanks！

**Comment by slrhs** [comment]
Traceback (most recent call last):
  File "vq2_zeroshot/vq2_vqa_blip2.py", line 12, in <module>
    model, vis_processors, _ = load_model_and_preprocess(name="blip2", model_type="pretrain", is_eval=True, device=device)
  File "/home/david/hyr/erasing/autodl-tmp/stable-diffusion-main/wysiwyr/LAVIS/lavis/models/__init__.py", line 205, in load_model_and_preprocess
    model = model_cls.from_pretrained(model_type=model_type)
  File "/home/david/hyr/erasing/autodl-tmp/stable-diffusion-main/wysiwyr/LAVIS/lavis/models/base_model.py", line 70, in from_pretrained
    model = cls.from_config(model_cfg)
  File "/home/david/hyr/erasing/autodl-tmp/stable-diffusion-main/wysiwyr/LAVIS/lavis/models/blip2_models/blip2_qformer.py", line 514, in from_config
    model = cls(
  File "/home/david/hyr/erasing/autodl-tmp/stable-diffusion-main/wysiwyr/LAVIS/lavis/models/blip2_models/blip2_qformer.py", line 71, in __init__
    self.Qformer, self.query_tokens = self.init_Qformer(
  File "/home/david/hyr/erasing/autodl-tmp/stable-diffusion-main/wysiwyr/LAVIS/lavis/models/blip2_models/blip2.py", line 54, in init_Qformer
    Qformer = BertLMHeadModel.from_pretrained(
  File "/home/david/anaconda3/envs/lavis/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2895, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/david/anaconda3/envs/lavis/lib/python3.8/site-packages/transformers/modeling_utils.py", line 467, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by LQY404** [comment]
hi, have you solve this problem, i find this problem in my task, could you give me hands, thanks.

**Comment by fancySummer19** [comment]
i encountered this problem in my task, have you solved the problem?
