### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'from_pretrained'

### ISSUE THREAD

**Issue by lyx-JuneSnow** [salesforce/LAVIS#724]
I have converted editing_tryon_zeroshot.ipynb in LAVIS\projects\blip-diffusion\notebooks to tryon.py.
Below is the code content of tryon.py.I did not change the original .ipynb file by converting it to a .py file.
```
import torch
from PIL import Image
from lavis.models import load_model_and_preprocess


# Load model and preprocess
model, vis_preprocess, txt_preprocess = load_model_and_preprocess("blip_diffusion", "base", device="cuda", is_eval=True)


# Define subjects and prompts
cond_subject = "dress"
src_subject = "dress"
tgt_subject = "dress"
text_prompt = "on a model"

# Preprocess text
src_subject = txt_preprocess["eval"](src_subject)
tgt_subject = txt_preprocess["eval"](tgt_subject)
cond_subject = txt_preprocess["eval"](cond_subject)
text_prompt = [txt_preprocess["eval"](text_prompt)]

# Preprocess images
cond_image_path = "/data/zzy/lyx/LAVIS/pink-dress.png"    # 填写condition_image位置
src_image_path = "/data/zzy/lyx/LAVIS/dress-model.png"    # 填写source_iamge位置
cond_image = Image.open(cond_image_path).convert("RGB")
cond_image = vis_preprocess["eval"](cond_image).unsqueeze(0).cuda()
src_image = Image.open(src_image_path).convert("RGB")

# Prepare samples
samples = {
    "cond_images": cond_image,
    "cond_subject": cond_subject,
    "src_subject": src_subject,
    "tgt_subject": tgt_subject,
    "prompt": text_prompt,
    "raw_image": src_image,
}

# Define parameters for editing
iter_seed = 88871
guidance_scale = 7.5
num_inference_steps = 50
num_inversion_steps = 50  # increase to improve DDIM inversion quality
lb_threshold = 0.15  # increase to edit fewer pixels
negative_prompt = "over-exposure, under-exposure, saturated, duplicate, out of frame, lowres, cropped, worst quality, low quality, jpeg artifacts, morbid, mutilated, out of frame, ugly, bad anatomy, bad proportions, deformed, blurry, duplicate"

# Perform editing
output = model.edit(
    samples,
    seed=iter_seed,
    guidance_scale=guidance_scale,
    num_inference_steps=num_inference_steps,
    num_inversion_steps=num_inversion_steps,
    neg_prompt=negative_prompt,
    lb_threshold=lb_threshold,
)

# Save output images
after_editing_path = '/data/zzy/lyx/LAVIS/test_result'   # 编辑后图片地址

output[1].save(after_editing_path)

print("=" * 30)

print("After editing:")
print(f"Image saved at: {after_editing_path}")

```
When I run this code, I get the following error:
```
(lyx_LAVIS) [zzy@localhost notebooks]$ python tryon.py
Traceback (most recent call last):
  File "tryon.py", line 7, in <module>
    model, vis_preprocess, txt_preprocess = load_model_and_preprocess("blip_diffusion", "base", device="cuda", is_eval=True)
  File "/data/zzy/anaconda3/envs/lyx_LAVIS/lib/python3.8/site-packages/lavis/models/__init__.py", line 195, in load_model_and_preprocess
    model = model_cls.from_pretrained(model_type=model_type)
AttributeError: 'NoneType' object has no attribute 'from_pretrained'
```
So I tracked down the location of the load_model_and_preprocess function：
```
def load_model_and_preprocess(name, model_type, is_eval=False, device="cpu"):
    """
    Load model and its related preprocessors.

    List all available models and types in registry:
    >>> from lavis.models import model_zoo
    >>> print(model_zoo)

    Args:
        name (str): name of the model.
        model_type (str): type of the model.
        is_eval (bool): whether the model is in eval mode. Default: False.
        device (str): device to use. Default: "cpu".

    Returns:
        model (torch.nn.Module): model.
        vis_processors (dict): preprocessors for visual inputs.
        txt_processors (dict): preprocessors for text inputs.
    """
    model_cls = registry.get_model_class(name)

    # load model
    model = model_cls.from_pretrained(model_type=model_type)


    if is_eval:
        model.eval()

    # load preprocess
    cfg = OmegaConf.load(model_cls.default_config_path(model_type))
    if cfg is not None:
        preprocess_cfg = cfg.preprocess

        vis_processors, txt_processors = load_preprocess(preprocess_cfg)
    else:
        vis_processors, txt_processors = None, None
        logging.info(
            f"""No default preprocess for model {name} ({model_type}).
                This can happen if the model is not finetuned on downstream datasets,
                or it is not intended for direct use without finetuning.
            """
        )

    if device == "cpu" or device == torch.device("cpu"):
        model = model.float()

    return model.to(device), vis_processors, txt_processors
```
With the help of this comment
```
    List all available models and types in registry:
    >>> from lavis.models import model_zoo
    >>> print(model_zoo)
```
I found all the existing models, as follows:
```
(lyx_LAVIS) [zzy@localhost notebooks]$ python -c "from lavis.models import model_zoo; print(model_zoo)"
==================================================
Architectures                  Types
==================================================
albef_classification           ve
albef_feature_extractor        base
albef_nlvr                     nlvr
albef_pretrain                 base
albef_retrieval                coco, flickr
albef_vqa                      vqav2
alpro_qa                       msrvtt, msvd
alpro_retrieval                msrvtt, didemo
blip_caption                   base_coco, large_coco
blip_classification            base
blip_feature_extractor         base
blip_image_text_matching       base, large
blip_nlvr                      nlvr
blip_pretrain                  base
blip_retrieval                 coco, flickr
blip_vqa                       vqav2, okvqa, aokvqa
blip2_opt                      pretrain_opt2.7b, pretrain_opt6.7b, caption_coco_opt2.7b, caption_coco_opt6.7b
blip2_t5                       pretrain_flant5xl, pretrain_flant5xl_vitL, pretrain_flant5xxl, caption_coco_flant5xl
blip2_feature_extractor        pretrain, pretrain_vitL, coco
blip2                          pretrain, pretrain_vitL, coco
blip2_image_text_matching      pretrain, pretrain_vitL, coco
pnp_vqa                        base, large, 3b
pnp_unifiedqav2_fid            
img2prompt_vqa                 base
clip_feature_extractor         ViT-B-32, ViT-B-16, ViT-L-14, ViT-L-14-336, RN50
clip                           ViT-B-32, ViT-B-16, ViT-L-14, ViT-L-14-336, RN50
gpt_dialogue                   base
```
I didn't find the blip_diffusion model. But now I downloaded blipdiffusion from huggingface. What should I do next?

**Comment by gemmact** [comment]
any progress with this? I'm finding the same issue

**Comment by Jeonghoon4** [comment]
I also had a similar problem and solved it by referring to [that issue](https://github.com/salesforce/LAVIS/issues/762#issuecomment-2482252898). I'm not sure if it'll help, but it might be worth trying.

Error
![Image](https://github.com/user-attachments/assets/df12f5f0-e91c-4b68-8860-c64718b42b3f)

Solution
```
conda create -n lavis python=3.11 -y  
conda activate lavis  
pip install --upgrade pip  
pip install salesforce-lavis  
pip install opencv-python 
```

**Comment by Mohammad-Reza-Eslami** [comment]
Hi, I had the same error, 'NoneType' object has no attribute 'from_pretrained'. You should upgrade your transformers.
I updated to version 4.48.2 and it worked fine!
