### ISSUE TITLE
您好，在运行instructblip的run_damo时候遇到如下问题，但是并未找到设置repo_type的地方

### ISSUE THREAD

**Issue by luyhhhhh** [salesforce/LAVIS#728]
Traceback (most recent call last):
  File "D:\PycharmProjects\LAVIS-main\projects\instructblip\run_demo.py", line 82, in <module>
    model, vis_processors, _ = load_model_and_preprocess(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\LAVIS-main\lavis\models\__init__.py", line 205, in load_model_and_preprocess
    model = model_cls.from_pretrained(model_type=model_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\LAVIS-main\lavis\models\base_model.py", line 70, in from_pretrained
    model = cls.from_config(model_cfg)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\LAVIS-main\lavis\models\blip2_models\blip2_vicuna_instruct.py", line 715, in from_config
    model = cls(
            ^^^^
  File "D:\PycharmProjects\LAVIS-main\lavis\models\blip2_models\blip2_vicuna_instruct.py", line 90, in __init__
    self.llm_tokenizer = LlamaTokenizer.from_pretrained(llm_model, use_fast=False, truncation_side="left")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\LAVIS-main\.venv\Lib\site-packages\transformers\tokenization_utils_base.py", line 1813, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
                                    ^^^^^^^^^^^^
  File "D:\PycharmProjects\LAVIS-main\.venv\Lib\site-packages\transformers\utils\hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\LAVIS-main\.venv\Lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\LAVIS-main\.venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\PycharmProjects\LAVIS-main\.venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './llm/vicuna-7b'. Use `repo_type` argument if needed.

**Comment by ddkkgit** [comment]
you can set llm_model='your path', the vicuna pretrain model needs you manual download in https://huggingface.co/lmsys/vicuna-7b-v1.5
for example:
llm_model="D/test/vicuna-7v"
self.llm_tokenizer = LlamaTokenizer.from_pretrained(llm_model, use_fast=False, truncation_side="left)
